config/routes.rb
Shop::Application.routes.draw do
  # Generate the routing paths for admins and users via devise gem
  devise_for :admins, :users
  
  # Generic form of generating RESTful routes for RESful controllers
  resources :line_items
  
  resources :carts, path: "basket" # Modified the wording used to represent the shopping cart in the URI
  
  resources :orders do
    # This allows the Kaminari gem to paginate on a collection, in this case orders, in any of its views
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :expansions do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :categories do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :products, path: "cards" do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  resources :home do
    get ':page', :action => :index, :on => :collection
  end
  
  # Create the search route
  match 'search' => 'search#index', :as => :search
  
  # Create the about root
  match 'about' => 'home#about', :as => :about
  
  # Set the entry point to the application
  root :to => "home#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  # creates getter and setter methods for the listed attributes
  attr_accessible :name
  
  # establishes a association with the Product model
  has_many :products
end

app/controllers/categories_controller.rb
# This is a very generic controller

class CategoriesController < ApplicationController
  # Making sure users are authenticated as an admin to 
  # view the actions in this controller, except the show action
  before_filter :authenticate_admin!, :except => [:show]

  def index
    # paginate the results, 15 per page (all pagination takes this form)
    @categories = Category.page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def show
    # get the category object for the passed ID
    @category = Category.find(params[:id])
    # get all the products where the category_id (foreign key) 
    # is the same as the passed ID, then paginate results, 9 per page
    @products = Product.where("category_id = ?", params[:id]).page(params[:page]).per(9)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% title 'Listing Categories' %>

<h1>Listing categories</h1>

<p><%= link_to 'Add New Category', new_category_path, :class => 'button' %></p>

<div class="listing">
	<table>
	  <tr>
	    <th>Name</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @categories.each do |category| %>
	  <tr>
	    <td><%= category.name %></td>
	    <td><%= link_to 'Show', category %></td>
	    <td><%= link_to 'Edit', edit_category_path(category) %></td>
	    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
	</table>
</div>
<div class="pagi">
	<%= paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% title(@category.name.pluralize) %>

<h1><%= @category.name.pluralize %></h1>

<div class="listing">
	<% @products.each do |product| %>
		<div>
			<div><%= link_to(image_tag(product.image, width: '160', alt: product.title, title: product.title), product) %></div>
			<p class="card_name"><%= link_to product.title, product, title: product.title %></p>
			<div class="cta">
				<span class="price"><%= number_to_currency product.price %></span>
				<% if user_signed_in? %>
					<span><%= button_to 'Add to Basket', line_items_path(product_id: product), :class => 'button', remote: true %></span>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
<div class="pagi">
	<%= paginate @products %>
</div>