config/routes.rb
Shop::Application.routes.draw do
  # Generate the routing paths for admins and users via devise gem
  devise_for :admins, :users
  
  # Generic form of generating RESTful routes for RESful controllers
  resources :line_items
  
  resources :carts, path: "basket" # Modified the wording used to represent the shopping cart in the URI
  
  resources :orders do
    # This allows the Kaminari gem to paginate on a collection, in this case orders, in any of its views
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :expansions do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :categories do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :products, path: "cards" do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  resources :home do
    get ':page', :action => :index, :on => :collection
  end
  
  # Create the search route
  match 'search' => 'search#index', :as => :search
  
  # Create the about root
  match 'about' => 'home#about', :as => :about
  
  # Set the entry point to the application
  root :to => "home#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
  # creates getter and setter methods for the listed attributes
  attr_accessible :description, :image, :price, :title, :category_id, :expansion, :expansion_id
  
  # mounts a CarrierWave uploader onto this model
  mount_uploader :image, ImageUploader
  
  # establishes an association between this model and the ones listed
  belongs_to :category
  belongs_to :expansion
  has_many :line_items
  
  # before a Product is destroyed, ensure none are referenced by a LineItem
  before_destroy :ensure_not_referenced_by_any_line_item
  
  # ensures the listed attributes are filled in when a new Product is created
  validates :description, :image, :price, :title, presence: true
  
  # adds Sunspot indexing to the title and description attributes
  # the title attribute is ranked as more important (boost: 5)
  searchable do
    text :title, boost: 5
    text :description
  end
  
  private
    
    # checks if a product is associated to any line item (checked through association)
    def ensure_not_referenced_by_any_line_item
      if line_items.count.zero?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Making sure users are authenticated as an admin to 
  # view the actions in this controller, except the show action
  before_filter :authenticate_admin!, except: [:show]

  def index
    @products = Product.page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # Tries to find a product by a passed ID
  # If no record was found, and error is thrown and the user is 
  # redirected to the home page, else the page is rendered normally
  def show
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid product #{params[:id]}"
      redirect_to home_index_url, alert: "Invalid Product"
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product }
      end
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
	<div class="field">
    <%= f.label :category %>
		<%= f.collection_select(:category_id, @categories, :id, :name) %>
  </div>
	<div class="field">
    <%= f.label :expansion %>
		<%= f.collection_select(:expansion_id, @expansions, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% title 'Editing Product' %>

<h1>Editing product</h1>

<%= render 'form' %>

<p class="links">
	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</p>

app/views/products/index.html.erb
<% title("Listing Products") %>

<h1>Listing Products</h1>

<% if admin_signed_in? %>
	<p><%= link_to 'Add New Product', new_product_path, :class => 'button' %></p>
<% end %>

<div class="listing">
	<table>
		<tr>
			<th>Image</th>
			<th>Name</th>
			<th>Category</th>
			<th>Expansion</th>
			<th>Price</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</tr>
		<% @products.each do |product| %>
			<tr>
				<td class="image"><%= link_to(image_tag(product.image, size: '45x60', alt: product.title, title: product.title), product) %></td>
				<td><%= link_to product.title, product, title: product.title %></td>
				<td><%= product.category.name %></td>
				<td><%= product.expansion.name %></td>
				<td><%= number_to_currency product.price %></td>
				<td><%= link_to 'Edit', edit_product_path(product) %></td>
				<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</table>
</div>
<div class="pagi">
	<%= paginate @products %>
</div>

app/views/products/new.html.erb
<% title 'Add New Product' %>

<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% title @product.title %>

<div class="product">
	<div class="image"><%= image_tag @product.image %></div>
	<div class="details">
		<header>
			<h1><%= @product.title %></h1>
			<h2><%= @product.category.name %> - <%= @product.expansion.name %></h2>
		</header>		
		<%= simple_format @product.description %>
		<div class="buying">
			<p class="price">
			  Price: <span><%= number_to_currency @product.price %></span>
			</p>
			<div>
				<p>
					<% if user_signed_in? %>
						<%= button_to 'Add to Basket', line_items_path(product_id: @product), :class => 'button', remote: true %>
					<% else %>
					  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %> to buy this product.
					<% end %>
				</p>
			</div>
		</div>
	</div>
</div>