config/routes.rb
Shop::Application.routes.draw do
  # Generate the routing paths for admins and users via devise gem
  devise_for :admins, :users
  
  # Generic form of generating RESTful routes for RESful controllers
  resources :line_items
  
  resources :carts, path: "basket" # Modified the wording used to represent the shopping cart in the URI
  
  resources :orders do
    # This allows the Kaminari gem to paginate on a collection, in this case orders, in any of its views
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :expansions do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :categories do
    get ':id/page/:page', :action => :show, :on => :collection
  end

  resources :products, path: "cards" do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  resources :home do
    get ':page', :action => :index, :on => :collection
  end
  
  # Create the search route
  match 'search' => 'search#index', :as => :search
  
  # Create the about root
  match 'about' => 'home#about', :as => :about
  
  # Set the entry point to the application
  root :to => "home#index"
end

app/views/layouts/_categories.html.erb
<% @categories.each do |cat| %>
	<li><%= link_to cat.name, cat %></li>
<% end %>

app/views/layouts/_expansions.html.erb
<% @expansions.each do |exp| %>
	<li><%= link_to exp.name, exp %></li>
<% end %>

app/views/layouts/_menu.html.erb
<h3 class="border_me">Categories</h3>
<ul class="menu">
	<%= render 'layouts/categories' %>
</ul>
<h3>Expansions</h3>
<ul class="menu">
	<%= render 'layouts/expansions' %>
</ul>

app/views/layouts/_user_nav.html.erb
<!-- this template determines what kind of user is logged in (admin/user)
and shows the appropriate links based on their privilege -->
<% if user_signed_in? %>
	<span><span>Signed in as:</span> <%= current_user.email %></span>
<% end %>
<ul>
	<% if !admin_signed_in? %>
		<li><%= link_to 'About', :about %></li>
		<% if !user_signed_in? %>
			<li><%= link_to "Create Account", new_user_registration_path %></li>
			<li><%= link_to "Sign In", new_user_session_path %></li>
		<% else %>
			<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			<%= content_tag(:li, link_to("My Basket", cart_path(@cart))) %>
			<li><%= link_to 'Checkout', new_order_path %></li>
		<% end %>
	<% end %>
	<% if admin_signed_in? %>
		<li><%= link_to "Orders", orders_path %></li>
		<li><%= link_to "Categories", categories_path %></li>
		<li><%= link_to "Expansions", expansions_path %></li>
		<li><%= link_to "Products", products_path %></li>
		<li><%= link_to "Sign Out (Admin)", destroy_admin_session_path, method: :delete %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- inserting the value of the title helper method into the layout -->
	<title>The Mythic Shop - <%= yield :title %></title>
	<!-- loads in all the stylesheets -->
  <%= stylesheet_link_tag "application", :media => "all" %>
	<!-- produces a Cross Site Request Forgery meta tag to make sure request are legit -->
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<section id="user_bar">
		<section class="wrapper">
			<!-- renders the user navigation at the top of the page -->
			<%= render 'layouts/user_nav' %>
		</section>
	</section>
	<header>
		<section class="wrapper">
			<div class="title">
				<%= link_to 'The Mythic Shop', :root %>
			</div>
			<div class="search">
				<!-- search form generation -->
				<%= form_tag search_path, method: :get do %>
					<div>
						<%= text_field_tag :term, params[:term], id: 'autocomplete' %>
						<%= submit_tag "Search", id: 'search_button', name: nil %>
					</div>
				<% end %>
			</div>
		</section>
	</header>
	<!-- shows messages from the system to the user if they exist -->
	<% if flash[:notice].present? %>
		<section class="msg notice">
			<p class="wrapper"><%= flash[:notice] %></p>
		</section>
	<% elsif flash[:alert].present? %>
		<section class="msg alert">
			<p class="wrapper"><%= flash[:alert] %></p>
		</section>
	<% end %>
	<section class="container">		
		<section class="wrapper">
			<section id="left">
				<!-- if the @cart object is available to the view -->
				<% if @cart %>
					<!-- show the shopping cart -->
					<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
						<!-- render the cart partial, specifying the path to the partial 
						and the passed object to avoid a conflict with the devise gem -->
						<%= render partial: 'carts/cart', object: @cart %>
					<% end %>
				<% end %>
				<!-- render the menu partial -->
				<%= render 'layouts/menu' %>
			</section>
			<section id="main">
				<!-- render the contents of the current view -->
				<%= yield %>
			</section>
		</section>
	</section>		
	<footer>
		<section class="wrapper">
			<section>
				<h3>Categories</h3>
				<ul>
					<!-- render the categories list -->
					<%= render 'layouts/categories' %>
				</ul>
			</section>
			<section>
				<h3>Expansions</h3>
				<ul>
					<!-- render the expansions list -->
					<%= render 'layouts/expansions' %>
				</ul>
			</section>
			<section>
				<h3>This is not a real shop</h3>
				<p>Please see the <%= link_to 'about', about_path %> page for more information about this website.</p>
			</section>
		</section>
	</footer>
	<!-- insert the javascript files into the view,
	these are inserted last to improve page performance -->
	<%= javascript_include_tag "application" %>
</body>
</html>